version: '2'
services:
  origin:
    command: "bin/rails server --port 3000 --bind '0.0.0.0'"
    build:
      context: ./origin
    volumes:
      - ./origin:/usr/lib/origin
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - memcached
      - proxy
    environment:
      - RAILS_ENV=development
      - ORIGIN_ENCRYPTION_PRIVATE=7252a81d820bb7cd88fe35224b7b51f271a2f8fa5a092424bcafc1d1e5109cd47e2095ff50febc1a496d64fc8c016d634263e058812752c0ec9e3f3b07b72a4c
      - ORIGIN_ENCRYPTION_SALT=4eef1c3ac67dc26dbb48dcc3288babadcab7c4e5811dd8129ceccb04391ed33cd237be669116ae5324dfa04f7f04d2b6a311b7330348d2da43759e25518ae21a
      - RAILS_SESSION_PRIVATE=7252a81d820bb7cd88fe35224b7b51f271a2f8fa5a092424bcafc1d1e5109cd47e2095ff50febc1a496d64fc8c016d634263e058812752c0ec9e3f3b07b72a4c
      - ORIGIN_LOCATION=http://origin.lacqueristas.local
      - WWW_LOCATION=http://www.lacqueristas.local
      - VIRTUAL_HOST=origin.lacqueristas.local
  www:
    command: "npm run start"
    build:
      context: ./www
    volumes:
      - ./www:/usr/lib/www
    ports:
      - "3001:3001"
    depends_on:
      - memcached
      - proxy
    environment:
      - NODE_ENV=development
      - ORIGIN_LOCATION=http://origin.lacqueristas.local
      - WWW_LOCATION=http://www.lacqueristas.local
      - VIRTUAL_HOST=www.lacqueristas.local
  postgres:
    image: postgres:9.6.1-alpine
    ports:
      - "5432:5432"
  memcached:
    image: memcached:1.4.34-alpine
    ports:
      - "11211:11211"
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
