version: '2'
services:
  origin:
    build:
      context: ./origin
    volumes:
      - ./origin:/usr/lib/origin
    depends_on:
      - postgres
      - memcached
      - proxy
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=postgres
      - ORIGIN_ENCRYPTION_PRIVATE=7252a81d820bb7cd88fe35224b7b51f271a2f8fa5a092424bcafc1d1e5109cd47e2095ff50febc1a496d64fc8c016d634263e058812752c0ec9e3f3b07b72a4c
      - ORIGIN_ENCRYPTION_SALT=4eef1c3ac67dc26dbb48dcc3288babadcab7c4e5811dd8129ceccb04391ed33cd237be669116ae5324dfa04f7f04d2b6a311b7330348d2da43759e25518ae21a
      - RAILS_SESSION_PRIVATE=7252a81d820bb7cd88fe35224b7b51f271a2f8fa5a092424bcafc1d1e5109cd47e2095ff50febc1a496d64fc8c016d634263e058812752c0ec9e3f3b07b72a4c
      - ORIGIN_LOCATION=http://origin.lacqueristas.local
      - WWW_LOCATION=http://www.lacqueristas.local
      - LUMIN_LOCATION=http://lumin.lacqueristas.local
      - VIRTUAL_HOST=origin.lacqueristas.local
      - BUGSNAG_API_PRIVATE=cda4663b8f04520d2b6bc025d7325ea6
      - GOOGLE_CLOUD_PROJECT=lacqueristas
      - GOOGLE_CLOUD_PUBSUB_TOPIC=development
  www:
    build:
      context: ./www
    volumes:
      - ./www:/usr/lib/www
    depends_on:
      - memcached
      - proxy
    environment:
      - BUGSNAG_API_PRIVATE=703d5caeb76c1ea38d1c0078fa169977
      - BUGSNAG_API_PUBLIC=65eccb16c964ea80775c5cc74f3922c3
      - NODE_ENV=development
      - ORIGIN_LOCATION=http://origin.lacqueristas.local
      - WWW_LOCATION=http://www.lacqueristas.local
      - LUMIN_LOCATION=http://lumin.lacqueristas.local
      - VIRTUAL_HOST=www.lacqueristas.local
  lumin:
    build:
      context: ./lumin
    volumes:
      - ./lumin:/usr/lib/lumin
    depends_on:
      - proxy
    environment:
      - NODE_ENV=development
      - ORIGIN_LOCATION=http://origin.lacqueristas.local
      - WWW_LOCATION=http://www.lacqueristas.local
      - LUMIN_LOCATION=http://lumin.lacqueristas.local
      - GOOGLE_CLOUD_PROJECT=lacqueristas
      - GOOGLE_CLOUD_KEY_FILENAME=googleCloud.secret.json
      - GOOGLE_CLOUD_STORAGE_BUCKET=lacqueristas-development
      - VIRTUAL_HOST=lumin.lacqueristas.local
  postgres:
    image: postgres:9.5.7-alpine
    logging:
      driver: "none"
    environment:
      - VIRTUAL_HOST=postgres.lacqueristas.local
  memcached:
    image: memcached:1.4.34-alpine
    logging:
      driver: "none"
    environment:
      - VIRTUAL_HOST=memcached.lacqueristas.local
  proxy:
    image: jwilder/nginx-proxy
    logging:
      driver: "none"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/:/etc/nginx/conf.d/
